dist: bionic

matrix:
  include:
    - name: "clang static analysis"
      if: type = pull_request OR type = api OR type = cron
      language: cpp
      compiler:
        - clang
      before_install:
        - cd ~/; git clone https://github.com/amrex-codes/amrex
        - cd ~/amrex; git checkout development
        - cd ~/; git clone https://github.com/starkiller-astro/Microphysics.git
        - cd ~/Microphysics; git checkout development
        - cd $TRAVIS_BUILD_DIR
      addons:
        apt:
          packages:
          - g++
          - gfortran
          - libgmp-dev
          - libmpfr-dev
          - python3
      before_script:
        - export AMREX_HOME=~/amrex
        - export MICROPHYSICS_HOME=~/Microphysics
      script:
        - cd $TRAVIS_BUILD_DIR/Exec/science/wdconvect; scan-build -enable-checker security.FloatLoopCounter -enable-checker security.insecureAPI.UncheckedReturn make -j 2 USE_OMP=FALSE USE_MPI=FALSE USE_CUDA=FALSE DIM=3 DEBUG=TRUE 2>&1 | tee clang_analysis.txt
        - python3 $TRAVIS_BUILD_DIR/Util/scripts/clang_static_analysis.py clang_analysis.txt