name: Tab exterminator

on:
  pull_request:
    branches: development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Run tab exterminator script
      run: |
        cd Util/scripts
        ./tab_exterminator.sh

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add --all
        git diff-index --quiet HEAD || git commit -m "Tabs have been converted to spaces by tab_exterminator.sh"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.head_ref }}
